### ISSUE TITLE
Is it possible to make this image smaller?

### ISSUE THREAD

**Issue by resouer** [Hyzual/docker-gitolite-http#1]
Thanks hyzual ! This repo is great!

But is there any way to make this image smaller? 150M is too big for my env, half is better.

I'm not perl expert, but is locale deb is necessary? Or is there any pkg actually not needed?

What I need is quite simple, just start up the git server, and then clone a testing repo from it to local.

**Comment by Hyzual** [comment]
Hi, thanks for your interest :)

To be honest, I didn't spend too much time optimizing this image as getting it to work at all was a bit challenging. I'm no expert either, maybe the locale could be removed.
In any case, if you really need to halve the weight, I think the most promising way would be to switch the base image, maybe to [alpine](https://hub.docker.com/_/alpine/) instead of Debian.
It seems [apache](https://github.com/smebberson/docker-alpine/tree/master/alpine-apache) and [nginx](https://github.com/oren/alpine-nginx) can run on alpine, and I know there is also a package for git so technically I think it's possible to get gitolite with http running on alpine.

I'm a bit busy nowadays so I don't know when (if ?) I'll have the time to try that, if you can a PR is always welcome :)

**Comment by resouer** [comment]
Thanks for your reply, I can close this issue now.
